[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/projects"
  to = "/.netlify/functions/projects"
  status = 200

[[redirects]]
  from = "/api/save-projects"
  to = "/.netlify/functions/save-projects"
  status = 200

[[redirects]]
  from = "/api/upload-image"
  to = "/.netlify/functions/upload-image"
  status = 200
